[package]
name = "gitclass"
version = "0.1.0"
authors = ["mttaggart <michael.t.taggart@gmail.com>"]

[dependencies]
clap = {version = "2.13.0", features=["yaml"]}[dependencies.yaml-rust]

[dependences.yaml-rust]
git = "https://github.com/chyh1990/yaml-rust.git"
